music/urls.py
from django.urls import path, re_path
from music import views

app_name = 'music'

urlpatterns = [
    re_path(r'^artists-by-letter/(?P<letter>[a-z\*])/$', views.ArtistListByLetterView.as_view(), name='artist-list-by-letter'),
    path('artists/', views.ArtistListView.as_view(), name='artist-list'),
    path('artists/<slug:slug>/', views.ArtistDetailView.as_view(), name='artist-detail'),
    path('artists/<slug:slug>/delete/', views.ArtistDeleteView.as_view(), name='artist-delete'),

    # Admin views
    path('merge-artists/', views.MergeArtistsView.as_view(), name='merge-artists'),
    path('set-artist-name/', views.SetArtistNameView.as_view(), name='set-artist-name'),
]

radio/urls.py
from django.urls import path
from radio import views

app_name = 'radio'

urlpatterns = [
    path('stats/', views.StatsView.as_view(), name='stats'),
    path('stats/<slug:slug>/', views.RadioStatsView.as_view(), name='stats'),
    path('stats-redirect/', views.StatsRedirectView.as_view(), name='stats-redirect'),
    path('plays/', views.PlaysView.as_view(), name='plays'),
]

ui/urls.py
from django.urls import path
from ui import views

app_name = 'ui'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

music/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.functions import Lower

from radioscraper.postgres.lookups import ImmutableUnaccent


class Artist(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, unique=True, db_index=True)

    # Derived data, cached for performance
    play_count = models.IntegerField(default=0)

    def has_name(self, name):
        return self.names.filter(name=name).exists()

    def add_name(self, name):
        return ArtistName.objects.get_or_create(artist=self, name=name)

    def recalculate_derived_data(self):
        self.play_count = self.play_set.count()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class ArtistName(models.Model):
    """Artists can have multiple variations of their name"""

    artist = models.ForeignKey(Artist, CASCADE, related_name="names")
    name = models.CharField(max_length=255, unique=True, db_index=True)
    search = models.GeneratedField(
        expression=Lower(ImmutableUnaccent("name")),
        output_field=models.CharField(max_length=255, db_index=True),
        db_persist=True,
    )

music/views.py
import re

from django.contrib import messages
from django.contrib.postgres.lookups import Unaccent
from django.core.exceptions import ValidationError
from django.db import connection
from django.db.models.aggregates import Count
from django.db.models.functions import Lower
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import DeleteView, DetailView, ListView, TemplateView, View

from music.models import Artist, ArtistName
from music.utils import merge_artists
from radioscraper.mixins import UserIsStaffMixin
from radioscraper.postgres.lookups import ImmutableUnaccent


class ArtistListView(ListView):
    model = Artist
    paginate_by = 50

    def get_queryset(self):
        qs = super().get_queryset()
        query = self.request.GET.get('q', None)

        if query:
            return qs.filter(pk__in=self.find_artist_ids(query))

        return qs.none()

    def find_artist_ids(self, query):
        sql = """
        SELECT DISTINCT artist_id
        FROM music_artistname
        WHERE search LIKE '%%' || LOWER(IUNACCENT(%s)) || '%%'
        """

        with connection.cursor() as cursor:
            cursor.execute(sql, [query])
            data = cursor.fetchall()
            return [row[0] for row in data]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "q": self.request.GET.get('q'),
        })
        return context


class ArtistListByLetterView(ListView):
    template_name = 'music/artist_letter.html'
    model = Artist

    def dispatch(self, request, *args, **kwargs):
        self.letter = kwargs.get('letter')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        qs = super().get_queryset()

        if re.match("^[a-z]$", self.letter):
            return qs.filter(name__iunaccent__istartswith=self.letter)

        if self.letter == '*':
            from string import ascii_lowercase
            for c in ascii_lowercase:
                qs = qs.exclude(name__iunaccent__istartswith=c)
            return qs

        raise ValueError("Invalid letter, expected a-z or *")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "letter": self.letter
        })
        return context


class ArtistDetailView(DetailView):
    model = Artist

    def get_radios(self):
        return (self.object.play_set
            .values_list("radio__slug", "radio__name")
            .annotate(count=Count("*"))
            .order_by('-count'))

    def get_songs(self):
        return (self.object.play_set
            .values_list("title")
            .annotate(count=Count("*"))
            .order_by('-count'))[:10]

    def get_plays(self):
        return (self.object.play_set
            .prefetch_related('radio')
            .order_by('-timestamp'))[:20]

    def get_chart_data(self):
        return (self.object.play_set
            .extra(select={'day': "date_trunc('week', timestamp)"})
            .order_by('day')
            .values('day')
            .annotate(count=Count("*"))
            .values_list('day', 'count'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "plays": self.get_plays(),
            "radios": self.get_radios(),
            "songs": self.get_songs(),
            "chart_data": self.get_chart_data(),
        })
        return context


class ArtistDeleteView(UserIsStaffMixin, DeleteView):
    model = Artist
    template_name = 'music/artist_delete.html'

    def get_success_url(self):
        return reverse('music:artist-list')


class MergeArtistsView(UserIsStaffMixin, TemplateView):
    template_name = 'music/artist_merge.html'
    http_method_names = ['post']

    def get_artists(self):
        artist_ids = self.request.POST.getlist('artist')
        if not artist_ids:
            raise ValidationError("No artists to merge given")
        return Artist.objects.filter(pk__in=artist_ids)

    def get_target_artist(self):
        artist_id = self.request.POST.get('target_artist')
        if not artist_id:
            raise ValidationError("Target artist not given")
        return Artist.objects.get(pk=artist_id)

    def get_target_name(self):
        artist_id = self.request.POST.get('target_name')
        if not artist_id:
            raise ValidationError("Target name not given")
        return ArtistName.objects.get(pk=artist_id)

    def merge(self, request):
        target_artist = self.get_target_artist()
        target_name = self.get_target_name()
        artists = self.get_artists().exclude(pk=target_artist.pk)

        merge_artists(artists, target_artist, target_name)
        messages.info(request, "Artists merged")

        url = reverse("music:artist-detail", args=[target_artist.slug])
        return HttpResponseRedirect(url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "artists": self.get_artists(),
        })
        return context

    def post(self, request, *args, **kwargs):
        if self.request.POST.get('action') == 'Merge':
            try:
                return self.merge(request)
            except ValidationError as e:
                messages.error(request, e.message)

        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


class SetArtistNameView(UserIsStaffMixin, View):
    """
    Sets the default artist name.
    """
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        artist = Artist.objects.filter(pk=request.POST.get('artist')).first()
        name = ArtistName.objects.filter(pk=request.POST.get('name')).first()

        if not artist:
            messages.error(request, "Artist not given")

        if not name:
            messages.error(request, "ArtistName not given")

        if artist and name:
            artist.name = name.name
            artist.save()

        return HttpResponseRedirect(reverse("music:artist-detail", args=[artist.slug]))

music/templates/music/artist_delete.html
{% extends "ui/base.html" %}

{% load static radio %}

{% block title %}Delete artist {{ artist.name }}{% endblock %}

{% block content %}
<div class="container">
  <h1>Delete {{ artist.name }}</h1>

  Are you sure? This will also delete {{ artist.play_set.count }} plays.

  <form method="post">
    {% csrf_token %}
    <div class="button-group">
      <button class="alert button" type="submit">
        <i class="fa fa-times"></i> Delete
      </button>
      <a class="button" href="{% url 'music:artist-detail' artist.slug %}">
        <i class="fa fa-chevron-left"></i> Back
      </a>
    </div>
  </form>
</div>
{% endblock %}

music/templates/music/artist_detail.html
{% extends "ui/base.html" %}

{% load static radio %}

{% block title %}{{ artist.name }}{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'uPlot.min.css' %}" />
<style type="text/css">
#plays-chart {
  margin: 2rem 0;
  width: 100%;
  height: 400px;
}
</style>
{% endblock %}

{% block script %}
<script src="{% static 'uPlot.iife.min.js' %}"></script>

<script type="text/javascript">
  const element = document.getElementById("plays-chart");
  const xValues = [{% for k, v in chart_data %}{{ k|date_to_ts }},{% endfor %}];
  const yValues = [{% for k, v in chart_data %}{{ v }},{% endfor %}];

  (function() {
    const data = [xValues, yValues];
    const fmtDate = uPlot.fmtDate('{YYYY}-{MM}-{DD}');

    let opts = {
      title: "Weekly plays",
      width: element.clientWidth,
      height: element.clientHeight,
      series: [
        {
          label: "Week of",
          value: (self, ts) => ts ? fmtDate(new Date(ts * 1000)) : null,
        },
        {
          paths: uPlot.paths.bars(),
          fill: "SteelBlue",
          label: "Plays"
        }
      ],
    };

    const uplot = new uPlot(opts, data, element);

    function resize() {
      uplot.setSize({
        width: element.clientWidth,
        height: element.clientHeight - 60,  // Not sure why this is needed but uplot doesn't respect the height
      });
    }

    resize();
    window.addEventListener("resize", resize);
  })();
</script>
{% endblock %}

{% block content %}
<div class="container">

  <h1>{{ artist.name }}</h1>

  {% if user.is_superuser %}
  <div class="callout">
    <h3>Admin actions</h3>
    <div class="button-group">
      <a href="{% url 'music:artist-delete' artist.slug %}" class="button">Delete</a>
    </div>

    <h3>Choose default artist name</h3>

    <form action="{% url 'music:set-artist-name' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="artist" value="{{ artist.pk }}" />
      <ul>
      {% for name in artist.names.all %}
        <li>
          <label>
            <input type="radio" name="name" value="{{ name.pk }}" />
            {{ name.name }}
          </label>
        </li>
      {% endfor %}
      </ul>

      <button type="submit" class="button no-margin">Make default</button>
    </form>
  </div>
  {% endif %}

  <div class="columns">
    <div class="column">
      <h3>Most played by</h3>

      <table class="table">
        <thead>
          <tr>
            <th>Radio</th>
            <th>Play count</th>
          </tr>
        </thead>
        <tbody>
          {% for radio in radios %}
          <tr>
            <td>{{ radio.1 }}</td>
            <td>{{ radio.2 }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="column">
      <h3>Greatest hits</h3>

      <table class="table">
        <thead>
          <tr>
            <th>Song</th>
            <th>Play count</th>
          </tr>
        </thead>
        <tbody>
          {% for song in songs %}
          <tr>
            <td>{{ song.0 }}</td>
            <td>{{ song.1 }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <div id="plays-chart"></div>

  <h3>Recent plays</h3>

  <table class="table">
    <thead>
      <tr>
        <th>Timestamp</th>
        <th>Radio</th>
        <th>Song</th>
      </tr>
    </thead>
    <tbody>
      {% for play in plays %}
      <tr>
        <td>{{ play.timestamp }}</td>
        <td>{{ play.radio.name }}</td>
        <td>{{ play.title }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <a href="{% url 'radio:plays' %}?artist_name={{ artist.name|urlencode }}" class="button">See more &raquo;</a>
</div>
{% endblock %}

music/templates/music/artist_letter.html
{% extends "ui/base.html" %}

{% load static %}

{% block title %}Artists{% endblock %}

{% block content %}
<div class="container">
  <h1>Artists starting with {{ letter|upper }}</h1>

  <div class="callout">
    {% include "music/partial/letters.html" %}
  </div>

  {% if artist_list %}
    {% include "music/partial/artist_list.html" %}

    {% if is_paginated %}
      {% include "radio/partial/paging.html" %}
    {% endif %}
  {% else %}
    <p>No such artists found :/</p>
  {% endif %}
</div>
{% endblock %}

music/templates/music/artist_list.html
{% extends "ui/base.html" %}

{% load static %}

{% block title %}Artists{% endblock %}

{% block content %}
<div class="container">
  <h1>Artists</h1>

  <form method="get">
    <label for="search">Find artist</label>
    <input type="text" name="q" value="{{ q|default:"" }}" />
  </form>

  {% if artist_list %}
    <p>
      {% if is_paginated %}
        Showing first {{ artist_list.count }} artists. Narrow down your search.
      {% else %}
        Found {{ artist_list.count }} artists.
      {% endif %}
    </p>
    {% include "music/partial/artist_list.html" %}
  {% else %}
    <h3>Artists starting with...</h3>
    {% include "music/partial/letters.html" %}
  {% endif %}
</div>
{% endblock %}

music/templates/music/artist_merge.html
{% extends "ui/base.html" %}

{% load static radio %}

{% block title %}Merge artists{% endblock %}

{% block head %}
<style type="text/css">
  .table-top td { vertical-align: top }
</style>
{% endblock %}

{% block content %}
<div class="container">
  <h1>Merge artists</h1>

  <p>Pick the artist to merge into, and the desired default name.</p>

  <form method="post">
    {% csrf_token %}
    {% for artist in artists %}
      <input type="hidden" name="artist" value="{{ artist.pk }}" />
    {% endfor %}
    <table class="table table-top">
      <thead>
        <tr>
          <th>Artist</th>
          <th>Slug</th>
          <th>Plays</th>
          <th>Name alternatives</th>
        </tr>
      </thead>
      <tbody>
        {% for artist in artists %}
        <tr>
          <td>
            <label>
              <input type="radio" name="target_artist" value="{{ artist.pk }}" />
              {{ artist.name }}
            </label>
          </td>
          <td>
            {{ artist.slug }}
          </td>
          <td>
            {{ artist.play_set.count }}
          </td>
          <td>
            {% for name in artist.names.all %}
              <label>
                <input type="radio" name="target_name" value="{{ name.pk }}" />
                {{ name.name }}<br />
              </label>
            {% endfor %}
          </td>
          <td></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <input type="submit" name="action" value="Merge" class="button" />
  </form>
</div>
{% endblock %}