music/urls.py
from django.urls import path, re_path
from music import views

app_name = 'music'

urlpatterns = [
    re_path(r'^artists-by-letter/(?P<letter>[a-z\*])/$', views.ArtistListByLetterView.as_view(), name='artist-list-by-letter'),
    path('artists/', views.ArtistListView.as_view(), name='artist-list'),
    path('artists/<slug:slug>/', views.ArtistDetailView.as_view(), name='artist-detail'),
    path('artists/<slug:slug>/delete/', views.ArtistDeleteView.as_view(), name='artist-delete'),

    # Admin views
    path('merge-artists/', views.MergeArtistsView.as_view(), name='merge-artists'),
    path('set-artist-name/', views.SetArtistNameView.as_view(), name='set-artist-name'),
]

radio/urls.py
from django.urls import path
from radio import views

app_name = 'radio'

urlpatterns = [
    path('stats/', views.StatsView.as_view(), name='stats'),
    path('stats/<slug:slug>/', views.RadioStatsView.as_view(), name='stats'),
    path('stats-redirect/', views.StatsRedirectView.as_view(), name='stats-redirect'),
    path('plays/', views.PlaysView.as_view(), name='plays'),
]

ui/urls.py
from django.urls import path
from ui import views

app_name = 'ui'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

radio/models.py
import pytz

from datetime import datetime, timedelta

from django.db import models
from django.db.models import Count
from django.db.models.deletion import PROTECT
from django.db.models.functions.datetime import TruncDay

from radioscraper.utils.datetime import day_start, day_end
from radioscraper.utils.datetime import month_start, month_end


class RadioManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class Radio(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    active = models.BooleanField(default=True)
    offline = models.BooleanField(default=False, help_text="Show as offline in the UI")
    load = models.BooleanField(default=True, help_text="Run loaders for this radio")

    # Derived data, cached for performance
    first_play = models.ForeignKey("radio.Play", on_delete=PROTECT, blank=True, null=True, related_name="+")
    last_play = models.ForeignKey("radio.Play", on_delete=PROTECT, blank=True, null=True, related_name="+")
    play_count = models.PositiveIntegerField(default=0)

    objects = RadioManager()

    def get_first_play(self):
        return self.play_set.order_by('timestamp').first()

    def get_last_play(self):
        return self.play_set.order_by('-timestamp').first()

    def get_play_count(self):
        return self.play_set.count()

    def recalculate_derived_data(self):
        self.first_play = self.get_first_play()
        self.last_play = self.get_last_play()
        self.play_count = self.get_play_count()

    def plays(self, start=None, end=None):
        qs = self.play_set

        if start:
            qs = qs.filter(timestamp__gte=day_start(start))

        if end:
            qs = qs.filter(timestamp__lt=day_end(end))

        return qs

    def most_played_songs(self, start=None, end=None):
        return (self.plays(start, end)
                    .values('radio_id', 'artist_name', 'title')
                    .annotate(count=Count('*'))
                    .order_by("-count"))

    def most_played_daily(self, start=None, end=None):
        return (self.plays(start, end)
                    .annotate(day=TruncDay('timestamp'))
                    .values('radio_id', 'artist_name', 'title', 'day')
                    .annotate(count=Count('*'))
                    .order_by("-count"))

    @property
    def show_outage(self):
        if self.last_play:
            last = self.last_play.timestamp
            limit = datetime.now(pytz.UTC) - timedelta(days=1)
            return last < limit
        return False

    def __repr__(self):
        return 'Radio (name="{}")'.format(self.name)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class PlayManager(models.Manager):
    def month(self, year, month):
        """Returns plays within a given calendar month"""
        return self.get_queryset().filter(
            timestamp__gte=month_start(year, month),
            timestamp__lt=month_end(year, month)
        )


class Play(models.Model):
    radio = models.ForeignKey(Radio, on_delete=PROTECT)
    artist = models.ForeignKey('music.Artist', on_delete=models.CASCADE, null=True)
    artist_name = models.CharField(max_length=255, db_index=True)
    title = models.CharField(max_length=255, db_index=True)
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)

    objects = PlayManager()

    def __str__(self):
        return '"{}" by "{}"'.format(self.title, self.artist_name)

    def __repr__(self):
        return 'Play (title="{}" artist="{}"'.format(self.title, self.artist_name)

radio/views.py
from datetime import datetime, date
from urllib.parse import urlencode

from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, TemplateView, RedirectView

from radio.models import Radio, Play
from music.models import ArtistName
from radio.utils.stats import get_song_stats, get_artist_stats, get_most_played_artists

from radioscraper.utils.datetime import day_start, day_end
from radioscraper.utils.datetime import month_start, month_end


def get_year_month(request):
    today = date.today()
    default = [today.year, today.month]

    try:
        year = int(request.GET.get('year'))
        month = int(request.GET.get('month'))
    except:
        return default

    if year < 2000 or year > today.year or month < 1 or month > 12:
        return default

    return [year, month]


def stats_url(path, year, month, radio=None):
    if month < 1:
        month = 12
        year = year - 1

    if month > 12:
        month = 1
        year = year + 1

    today = date.today()
    if year < 2017 or year > today.year or (year == today.year and month > today.month):
        return None

    query = urlencode({
        "year": year,
        "month": month,
        "radio": radio,
    })

    return "{}?{}".format(path, query)


def prev_next_links(path, year, month, radio=None):
    return {
        "prev_month": stats_url(path, year, month - 1, radio),
        "next_month": stats_url(path, year, month + 1, radio),
        "prev_year": stats_url(path, year - 1, month, radio),
        "next_year": stats_url(path, year + 1, month, radio),
    }


class StatsRedirectView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        year, month = get_year_month(self.request)
        radio = self.request.GET.get("radio", "").strip()

        return "{}?{}".format(
            reverse("radio:stats", args=[radio] if radio else []),
            urlencode({"year": year, "month": month})
        )


class RadioStatsView(TemplateView):
    template_name = 'radio/radio_stats.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        slug = self.kwargs.get('slug')
        radio = get_object_or_404(Radio, slug=slug)

        year, month = get_year_month(self.request)
        start = month_start(year, month)
        end = month_end(year, month)

        play_count = radio.plays(start, end).count()

        context.update({
            "radio": radio,
            "month": month,
            "year": year,
            "play_count": play_count,
        })

        context.update(
            prev_next_links(self.request.path, year, month, radio.slug)
        )

        if play_count > 0:
            context.update({
                "song_stats": get_song_stats(start, end, radio.id),
                "artist_stats": get_artist_stats(start, end, radio.id),
                "most_played_songs": radio.most_played_songs(start, end)[:30],
                "most_played_artists": get_most_played_artists(radio, start, end)[:30],
                "most_played_daily": radio.most_played_daily(start, end).first()
            })

        return context


class StatsView(TemplateView):
    template_name = 'radio/stats.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        year, month = get_year_month(self.request)
        start = month_start(year, month)
        end = month_end(year, month)

        plays = Play.objects.month(year, month)
        play_count = plays.count()

        context.update({
            "month": month,
            "year": year,
            "play_count": play_count,
        })

        context.update(
            prev_next_links(self.request.path, year, month)
        )

        if play_count > 0:
            most_played_songs = (plays
                .values('artist_name', 'title')
                .annotate(count=Count('*'))
                .order_by('-count'))[:30]

            context.update({
                "song_stats": get_song_stats(start, end),
                "artist_stats": get_artist_stats(start, end),
                "most_played_songs": most_played_songs,
                "most_played_artists": get_most_played_artists(None, start, end)[:30],
            })

        return context


class PlaysView(ListView):
    template_name = 'radio/plays.html'
    model = Play
    limit = 100

    def _parse_date(self, value):
        try:
            return datetime.strptime(value, "%Y-%m-%d")
        except:
            return None

    def _parse_int(self, value):
        try:
            return int(value)
        except:
            return None

    def dispatch(self, *args, **kwargs):
        self.artist_name = self.request.GET.get('artist_name')
        self.title = self.request.GET.get('title')
        self.radio = self.request.GET.get('radio')
        self.start = self._parse_date(self.request.GET.get('start'))
        self.end = self._parse_date(self.request.GET.get('end'))
        self.from_id = self._parse_int(self.request.GET.get('from_id'))

        return super(PlaysView, self).dispatch(*args, **kwargs)

    def get_next_link(self, plays):
        if len(plays) < self.limit:
            return {}

        query = self.request.GET.copy()
        query["from_id"] = plays[-1].id - 1

        return "{}?{}".format(self.request.path, urlencode(query))

    def get_first_link(self):
        query = self.request.GET.copy()
        query.pop("from_id", None)

        return "{}?{}".format(self.request.path, urlencode(query))

    def get_context_data(self, **kwargs):
        context = super(PlaysView, self).get_context_data(**kwargs)

        plays = list(context["object_list"])

        if len(plays) > self.limit:
            plays = plays[:self.limit]
            next_link = self.get_next_link(plays)
        else:
            next_link = None

        context.update({
            'plays': plays,
            'radio': self.radio,
            'artist_name': self.artist_name,
            'title': self.title,
            'start': self.start,
            'end': self.end,
            'first_link': self.get_first_link(),
            'next_link': next_link,
        })
        return context

    def get_queryset(self):
        radio = Radio.objects.filter(slug=self.radio).first() if self.radio else None

        qs = (
            Play.objects
            .order_by("-id")
            .select_related('artist')
            .prefetch_related('radio')
        )

        if self.from_id:
            qs = qs.filter(id__lte=self.from_id)

        if radio:
            qs = qs.filter(radio=radio)

        if self.artist_name:
            # Removing ordering makes the query faster.
            # Using `.first()` adds ordering, so don't use it.
            artist_names = (
                ArtistName.objects
                .filter(name__iunaccent__iexact=self.artist_name)
                .order_by()
            )[:1]

            if artist_names:
                qs = qs.filter(artist_id=artist_names[0].artist_id)
            else:
                qs = qs.none()

        if self.title:
            qs = qs.filter(title__iunaccent__iexact=self.title)

        if self.start:
            qs = qs.filter(timestamp__gte=day_start(self.start))

        if self.end:
            qs = qs.filter(timestamp__lt=day_end(self.end))

        # One extra record is fetched to see if there is a next page
        return qs[:self.limit + 1]

radio/templates/radio/base.html
{% extends "radio/superbase.html" %}

{% block body %}
  <div class="top-bar-container">
    <div class="grid-container">
      <div class="top-bar">
        <div class="top-bar-left">
          <ul class="dropdown menu" data-dropdown-menu>
            <li>
              <a href="{% url 'radio:index' %}">Radio Scraper</a>
            </li>
            <li class="separator">//</li>
            <li>
              <a href="{% url 'radio:plays' %}">Plays</a>
            </li>
            <li class="separator">//</li>
            <li>
              <a href="{% url 'radio:stats' %}">Stats</a>
            </li>
            <li class="separator">//</li>
            <li>
              <a href="{% url 'music:artist-list' %}">Artists</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  {% include "radio/partial/messages.html" %}

  {% block content %}{% endblock %}
{% endblock %}

radio/templates/radio/index.html
{% extends "radio/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div id="index-page" class="grid-container">
    <h1>Radio scraper</h1>

    <p>Collecting radio playlists for no particular reason.</p>

    <p>
        <a href="{% url 'radio:plays' %}">List plays</a> ·
        <a href="{% url 'radio:stats' %}">Statistics</a>
    </p>

    <div class="grid-x grid-margin-x small-up-1 medium-up-2 large-up-4" data-equalizer>
        {% for radio in radios %}
        <div class="cell">
            <div class="radio" data-radio-link="{{ radio.slug }}" data-equalizer-watch>
                <h5>{{ radio.name }}</h5>
                <p>
                    {{ radio.play_count }} plays<br />
                    since {{ radio.first_play.timestamp|date:"d.m.Y" }}
                </p>
                <p>
                    Last play: <br />
                    <b>{{ radio.last_play.title }}</b>
                    by <b>{{ radio.last_play.artist_name }}</b><br />
                    at <i class="gray">{{ radio.last_play.timestamp|date:"Y-m-d @ H:i" }}</i>
                </p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

radio/templates/radio/plays.html
{% extends "ui/base.html" %}

{% load static %}

{% block title %}Plays{% endblock %}

{% block content %}
<div class="container">
  <form class="horizontal" action=".">
    <div class="form-row">
      <label for="start">From</label>
      <input type="date" id="start" name="start" value="{{ start|date:'Y-m-d' }}" />
    </div>

    <div class="form-row">
      <label for="start">Until</label>
      <input type="date" id="end" name="end" value="{{ end|date:'Y-m-d' }}" />
    </div>

    <div class="form-row">
      <label>Radio</label>
      <select data-radio-select name="radio" class="input-group-field">
        <option value=""{% if not radio %} selected{% endif %}>
          --- All ---
        </option>
        {% for r in radios %}
          <option value="{{ r.slug }}" {% if r.slug == radio %}selected{% endif %}>
            {{ r.name }}
          </option>
        {% endfor %}
      </select>
    </div>

    <div class="form-row">
      <label>Artist</label>
      <input name="artist_name" type="search" value="{{ artist_name|default:"" }}" placeholder="Search by artist">
    </div>

    <div class="form-row">
      <label>Title</label>
      <input name="title" type="search" value="{{ title|default:"" }}" placeholder="Search by title">
    </div>

    <div>
      <button class="button" type="submit">Search</button>
      <a href="{{ request.path }}" class="button">Clear</a>
    </div>
  </form>

  {% if plays %}
    {% include "radio/partial/next_first_buttons.html" %}

    <table id="plays-table" class="collapsible table">
      <thead>
        <tr>
          <th>Time</th>
          <th>Radio</th>
          <th>Artist</th>
          <th>Title</th>
        </tr>
      </thead>
      <tbody>
        {% for play in plays %}
          <tr>
            <td class="no-wrap">
              {{ play.timestamp }}
            </td>
            <td class="no-wrap">
              <a href="{% url 'radio:stats' play.radio.slug %}">{{ play.radio.name }}</a>
            </td>
            <td>
              <a href="{% url 'music:artist-detail' play.artist.slug %}">{{ play.artist_name }}</a><span class="show-mobile-only">:</span>
            </td>
            <td>
              {{ play.title }}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    {% include "radio/partial/next_first_buttons.html" %}
  {% else %}
    <h5>No plays matching given search parameters.</h5>
  {% endif %}
</div>
{% endblock %}

radio/templates/radio/radio_stats.html
{% extends "ui/base.html" %}

{% load static %}

{% block title %}Stats{% endblock %}

{% block content %}
<div class="container" id="stats-page">
  <h1>{{ radio.name }} stats</h1>

  {% include "radio/partial/time_radio_selector.html" %}

  {% if play_count > 0 %}
    <div class="columns">
      <div class="column">
        <h4>Song stats</h4>

        <table class="stats-table table">
          <tr>
            <th>Total songs played</th>
            <td>{{ play_count }}</td>
          </tr>
          <tr>
            <th>Distinct songs played</th>
            <td>{{ song_stats.distinct_count }}</td>
          </tr>
          <tr>
            <th>Songs played multiple times</th>
            <td>
              {{ song_stats.repeated_count }}
              ({{ song_stats.repeated_perc|floatformat }}%)
            </td>
          </tr>
          <tr>
            <th>Songs played only once</th>
            <td>
              {{ song_stats.single_play_count }}
              ({{ song_stats.single_play_perc|floatformat }}%)
            </td>
          </tr>
          <tr>
            <th>
              Most repeated song<br />in a single day
            </th>
            <td>
              {% with mrp=most_played_daily %}
                {{ mrp.artist_name }} - {{ mrp.title }}<br />
                <small>played {{ mrp.count }} times on {{ mrp.day.date }}</small>
              {% endwith %}
            </td>
          </tr>
        </table>
      </div>
      <div class="column">
        <h4>Artist stats</h4>

        <table class="stats-table table">
          <tr>
            <th>Distinct artists played</th>
            <td>{{ artist_stats.distinct_count }}</td>
          </tr>
          <tr>
            <th>Played multiple times</th>
            <td>
              {{ artist_stats.repeated_count }}
              ({{ artist_stats.repeated_perc|floatformat }}%)
            </td>
          </tr>
          <tr>
            <th>Played only once</th>
            <td>
              {{ artist_stats.single_play_count }}
              ({{ artist_stats.single_play_perc|floatformat }}%)
          </tr>
        </table>
      </div>
    </div>

    <div class="columns">

      {% if most_played_songs %}
      <div class="column">
        <h3>Top 30 songs</h3>

        <table class="table">
          <tr>
            <th class="text-center">Rank</th>
            <th>Song</th>
            <th class="text-center">Plays</th>
          </tr>
          {% for play in most_played_songs %}
          <tr>
            <td class="text-center">#{{ forloop.counter }}</td>
            <td>{{ play.artist_name }} - {{ play.title }}</td>
            <td class="text-center">{{ play.count }}</td>
          </tr>
          {% endfor %}
        </table>
      </div>
      {% endif %}

      {% if most_played_artists %}
      <div class="column">
        <h3>Top 30 artists</h3>

        <table class="table">
          <tr>
            <th class="text-center">Rank</th>
            <th>Artist</th>
            <th class="text-center">Plays</th>
          </tr>
          {% for artist in most_played_artists %}
          <tr>
            <td class="text-center">#{{ forloop.counter }}</td>
            <td>
              {% if artist.slug %}
              <a href="{% url 'music:artist-detail' artist.slug %}" class="">
                {{ artist.name }}
              </a>
              {% endif %}
            </td>
            <td class="text-center">{{ artist.count }}</td>
          </tr>
          {% endfor %}
        </table>
      </div>
      {% endif %}

    </div>
  {% else %}
    <p class="callout warning">No data exists for this period.</p>
  {% endif %}
</div>
{% endblock %}

radio/templates/radio/stats.html
{% extends "ui/base.html" %}

{% load static %}

{% block title %}Stats{% endblock %}

{% block content %}
<div class="container">
  <h1>Stats</h1>

  {% include "radio/partial/time_radio_selector.html" %}

  {% if play_count > 0 %}
    <h2>Song stats</h2>

    <table class="table">
      <tr>
        <th>Radio</th>
        <th>Distinct songs</th>
        <th class="text-center" colspan="2">Played once</th>
        <th class="text-center" colspan="2">Played multiple</th>
        <th>Repeated on average</th>
      </tr>
      {% for stats in song_stats %}
        <tr>
          <td>{{ stats.radio_name }}</td>
          <td>{{ stats.distinct_count }}</td>
          <td>{{ stats.single_play_count }}</td>
          <td>({{ stats.single_play_perc|floatformat }}%)</td>
          <td>{{ stats.repeated_count }}</td>
          <td>({{ stats.repeated_perc|floatformat }}%)</td>
          <td>{{ stats.avg_repetitions|floatformat }}</td>
        </tr>
      {% endfor %}
    </table>

    <h2>Artist stats</h2>

    <table class="table">
      <tr>
        <th>Radio</th>
        <th>Distinct artists</th>
        <th colspan="2">Played once</th>
        <th colspan="2">Played multiple</th>
        <th>Repeated on average</th>
      </tr>
      {% for stats in artist_stats %}
        <tr>
          <td>{{ stats.radio_name }}</td>
          <td>{{ stats.distinct_count }}</td>
          <td>{{ stats.single_play_count }}</td>
          <td>({{ stats.single_play_perc|floatformat }}%)</td>
          <td>{{ stats.repeated_count }}</td>
          <td>({{ stats.repeated_perc|floatformat }}%)</td>
          <td>{{ stats.avg_repetitions|floatformat }}</td>
        </tr>
      {% endfor %}
    </table>

    <div class="columns">
      {% if most_played_songs %}
      <div class="column">
        <h2>Top 30 songs</h2>

        <table class="table">
          <tr>
            <th>Rank</th>
            <th class="text-left">Song</th>
            <th>Played</th>
          </tr>
          {% for play in most_played_songs %}
          <tr>
            <td>#{{ forloop.counter }}</td>
            <td>{{ play.artist_name }} - {{ play.title }}</td>
            <td class="text-center">{{ play.count }}</td>
          </tr>
          {% endfor %}
        </table>
      </div>
      {% endif %}

      {% if most_played_artists %}
      <div class="column">
        <h2>Top 30 artists</h2>

        <table class="table">
          <tr>
            <th>Rank</th>
            <th class="text-left">Artist</th>
            <th>Played</th>
          </tr>
          {% for artist in most_played_artists %}
          <tr>
            <td>#{{ forloop.counter }}</td>
            <td>
              {% if artist.slug %}
              <a href="{% url 'music:artist-detail' artist.slug %}" class="">
                {{ artist.name }}
              </a>
              {% endif %}
            </td>
            <td class="text-center">{{ artist.count }}</td>
          </tr>
          {% endfor %}
        </table>
      </div>
      {% endif %}

    </div>
  {% else %}
    <p class="callout warning">No data exists for this period.</p>
  {% endif %}
</div>
{% endblock %}