dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("outages/<int:pk>", views.OutageDetailView.as_view(), name="outage-detail"),
    path("failures/<int:pk>", views.FailureDetailView.as_view(), name="failure-detail"),
]

ui/urls.py
from django.urls import path
from ui import views

app_name = 'ui'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

dashboard/views.py
from django.views.generic import DetailView, TemplateView
from loaders.models import Outage, LoaderFailure
from radioscraper.mixins import UserIsStaffMixin


class IndexView(UserIsStaffMixin, TemplateView):
    template_name = "dashboard/index.html"

    def get_context_data(self, **kwargs):
        active_outages = Outage.objects.filter(end__isnull=True).select_related("radio")
        recent_failures = LoaderFailure.objects.prefetch_related("radio").order_by("-id")[:50]

        context = super().get_context_data(**kwargs)
        context.update({
            "active_outages": active_outages,
            "recent_failures": recent_failures,
        })
        return context


class OutageDetailView(UserIsStaffMixin, DetailView):
    template_name = "dashboard/outage_detail.html"
    model = Outage

    def get_context_data(self, **kwargs):
        failures = self.object.failures.order_by("-timestamp")[:20]
        has_more = len(failures) < self.object.failure_count

        context = super().get_context_data(**kwargs)
        context.update({
            "failures": failures,
            "has_more": has_more,
        })
        return context


class FailureDetailView(UserIsStaffMixin, DetailView):
    template_name = "dashboard/failure_detail.html"
    model = LoaderFailure
    context_object_name = "failure"

dashboard/templates/dashboard/failure_detail.html
{% extends "ui/base.html" %}

{% block title %}Failure #{{ failure.pk }}{% endblock %}

{% block content %}
<div class="container">
  <h1>Failure #{{ failure.pk }}</h1>

  <p>
    Radio: {{ failure.radio }}<br />
    Timestamp: {{ failure.timestamp }}<br />
  </p>

  <h3>{{ failure.error_message }}</h3>

  <pre>{{ failure.stack_trace }}</pre>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends "ui/base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="container">
  <h1>Dashboard</h1>

  <p>Welcome dear admin!</p>

  {% if active_outages %}
    <h3>Active outages</h3>

    <table class="table">
      <thead>
        <tr>
          <th>Since</th>
          <th>Radio</th>
          <th>Failures</th>
        </tr>
      </thead>
      <tbody>
        {% for outage in active_outages %}
          <tr>
            <td>
              <a href="{% url 'dashboard:outage-detail' outage.pk %}">
                {{ outage.start }}
              </a>
            </td>
            <td>{{ outage.radio }}</td>
            <td>{{ outage.failure_count }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no active outages. \m/</p>
  {% endif %}

  {% if recent_failures %}
    <h3>Recent failures</h3>

    <table class="table">
      <thead>
        <tr>
          <th>Timestamp</th>
          <th>Radio</th>
          <th>Error message</th>
        </tr>
      </thead>
      <tbody>
        {% for failure in recent_failures %}
          <tr>
            <td>
              <a href="{% url 'dashboard:failure-detail' failure.pk %}">
                {{ failure.timestamp }}
              </a>
            </td>
            <td>{{ failure.radio.name }}</td>
            <td>{{ failure.error_message }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no active outages. \m/</p>
  {% endif %}
</div>
{% endblock %}

dashboard/templates/dashboard/outage_detail.html
{% extends "ui/base.html" %}

{% block title %}Outage #{{ outage.pk }}{% endblock %}

{% block content %}
<div class="container">
  <h1>Outage #{{ outage.pk }}</h1>

  <p>
    Radio: {{ outage.radio }}<br />
    Start: {{ outage.start }}<br />
    Failures: {{ outage.failure_count }}<br />
    End:
    {% if outage.end %}
      {{ outage.end }}
    {% else %}
      <em>Ongoing</em>
    {% endif %}
  </p>

  <h2>Failures</h2>

  {% if has_more %}
    <p><em>Showing last 20 failures</em></p>
  {% endif %}

  <table class="table">
    <tbody>
      {% for failure in failures %}
        <tr>
          <td>
            <a href="{% url 'dashboard:failure-detail' failure.pk %}">
              {{ failure.timestamp }}
            </a>
          </td>
          <td>{{ failure.error_message }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}