dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("outages/<int:pk>", views.OutageDetailView.as_view(), name="outage-detail"),
    path("failures/<int:pk>", views.FailureDetailView.as_view(), name="failure-detail"),
]

music/urls.py
from django.urls import path, re_path
from music import views

app_name = 'music'

urlpatterns = [
    re_path(r'^artists-by-letter/(?P<letter>[a-z\*])/$', views.ArtistListByLetterView.as_view(), name='artist-list-by-letter'),
    path('artists/', views.ArtistListView.as_view(), name='artist-list'),
    path('artists/<slug:slug>/', views.ArtistDetailView.as_view(), name='artist-detail'),
    path('artists/<slug:slug>/delete/', views.ArtistDeleteView.as_view(), name='artist-delete'),

    # Admin views
    path('merge-artists/', views.MergeArtistsView.as_view(), name='merge-artists'),
    path('set-artist-name/', views.SetArtistNameView.as_view(), name='set-artist-name'),
]

radio/urls.py
from django.urls import path
from radio import views

app_name = 'radio'

urlpatterns = [
    path('stats/', views.StatsView.as_view(), name='stats'),
    path('stats/<slug:slug>/', views.RadioStatsView.as_view(), name='stats'),
    path('stats-redirect/', views.StatsRedirectView.as_view(), name='stats-redirect'),
    path('plays/', views.PlaysView.as_view(), name='plays'),
]

ui/urls.py
from django.urls import path
from ui import views

app_name = 'ui'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

ui/views.py
from django.views.generic import TemplateView

from radio.models import Radio


class IndexView(TemplateView):
    template_name = 'ui/index.html'

    def get_context_data(self, **kwargs):
        radios = (Radio.objects.active()
            .order_by('name')
            .prefetch_related('first_play', 'last_play'))

        online_radios = [r for r in radios if not r.offline]
        offline_radios = [r for r in radios if r.offline]

        context = super().get_context_data(**kwargs)
        context.update({
            "online_radios": online_radios,
            "offline_radios": offline_radios,
        })
        return context

ui/templates/ui/base.html
{% extends "ui/superbase.html" %}

{% block body %}
  <header>
    <div class="container">
      <h1>
        <a href="{% url 'ui:index' %}">Radio Scraper</a>
      </h1>
      <a href="{% url 'radio:plays' %}">Plays</a>
      <span class="separator">//</span>
      <a href="{% url 'radio:stats' %}">Stats</a>
      <span class="separator">//</span>
      <a href="{% url 'music:artist-list' %}">Artists</a>
      {% if user.is_authenticated %}
        <span class="separator">//</span>
        <a href="{% url 'dashboard:index' %}">Dashboard</a>
      {% endif %}
    </div>
  </header>

  <main>
    {% include "ui/partial/messages.html" %}
    {% block content %}{% endblock %}
  </main>

  <footer>
    <div>
      Radioscraper is <a href="https://github.com/ihabunek/radioscraper/">open source</a>
      <br class="show-mobile-only" />
      <span class="separator">♥</span>
      <br class="show-mobile-only" />
      Authored by <a href="https://bsky.app/profile/ivan.habunek.com">@ihabunek</a>
    </div>
  </footer>
{% endblock %}

ui/templates/ui/index.html
{% extends "ui/base.html" %}

{% load radio %}

{% block title %}Home{% endblock %}

{% block content %}
<div id="index-page" class="container">
  <h1>Radio scraper</h1>

  <p>Collecting radio playlists for no particular reason.</p>

  <div id="radio-search">
      <input id="radio-search-input" type="text" placeholder="Search radios..." />
      {% include "ui/partial/radios.html" with radios=online_radios %}
  </div>

  {% if offline_radios %}
    <h2 style="margin-top: 2rem">Offline stations</h2>
    <p>Stations which are no more :(</p>

    {% include "ui/partial/radios.html" with radios=offline_radios %}
  {% endif %}
</div>

<script>
(function() {
  const input = document.getElementById("radio-search-input");
  input.addEventListener("input", filterRadios);
  input.style.display = "block"; // Hidden by default
  input.value = "";
  filterRadios();
})()

function filterRadios() {
  const input = document.getElementById("radio-search-input");
  const search = input.value.trim().toLowerCase();

  const container = document.getElementById("radio-search");
  const radios = container.getElementsByClassName("radio");
  for (radio of radios) {
    radio.style.display = visibility(radio, search);
  }
}

function visibility(element, search) {
  const name = radio.dataset.name.toLowerCase();
  return name.includes(search) ? "block" : "none";
}
</script>
{% endblock %}

ui/templates/ui/superbase.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} - Radio scraper</title>
    <link rel="stylesheet" type="text/css" href="{% static "styles.css" %}">
    {% block head %}{% endblock %}
</head>
<body>
  {% block body %}{% endblock %}
</body>
{% block script %}{% endblock %}
</html>